"use client";
import {useState} from "react";
const countries=["Pakistan","UAE","USA","UK","India","Saudi Arabia","Other"];
const categories=["Food & Restaurants","Fashion & Beauty","Technology & Startups","Ecommerce","Creators & Influencers","Agencies & Services","Entertainment","Other"];
export default function Join(){
 const [step,setStep]=useState(1); const [data,setData]=useState({name:"",tagline:"",country:"",category:"",url:"",bid:"100",logo:""});
 const set=(k,v)=>setData({...data,[k]:v});
 const next=e=>{e.preventDefault();setStep(step+1)};
 if(step===4)return <main className="joinPage"><div className="joinCard success"><a className="logo" href="/">UP<span>BIDO</span><i>↗</i></a><div className="step">DEMO LISTING CREATED</div><h1>You're on<br/><em>the board.</em></h1><p><b>{data.name}</b> is now in the demo battle. No real payment was made.</p><div className="rankGrid"><div><span>GLOBAL</span><b>#248</b></div><div><span>{data.country.toUpperCase()}</span><b>#19</b></div><div><span>CATEGORY</span><b>#7</b></div></div><a className="primary btnlink" href="/dashboard">OPEN MY DASHBOARD →</a></div></main>;
 return <main className="joinPage"><div className="joinTop"><a className="logo" href="/">UP<span>BIDO</span><i>↗</i></a><span className="progress">STEP {step} OF 3</span><a href="/">← BACK</a></div><div className="joinGrid"><section><div className="step">JOIN THE BATTLE · DEMO MODE</div><h1>{step===1?"Build your":step===2?"Pick your":"Place your"}<br/><em>{step===1?"profile.":step===2?"arena.":"bid."}</em></h1><p>{step===1?"Tell people who you are and where to find you.":step===2?"Your listing competes globally, locally and in its category.":"Choose your demo bid. Higher eligible bids rank higher."}</p><div className="joinFacts"><div className={step===1?"activeFact":""}><b>01</b><span>Create your profile</span></div><div className={step===2?"activeFact":""}><b>02</b><span>Choose your arena</span></div><div className={step===3?"activeFact":""}><b>03</b><span>Place a demo bid</span></div></div></section>
 {step===1&&<form onSubmit={next}><label>BRAND / CREATOR NAME<input required value={data.name} onChange={e=>set("name",e.target.value)} placeholder="e.g. Bake House"/></label><label>TAGLINE<input required value={data.tagline} onChange={e=>set("tagline",e.target.value)} placeholder="Tell the world what you do"/></label><label>WEBSITE OR SOCIAL URL<input required type="url" value={data.url} onChange={e=>set("url",e.target.value)} placeholder="https://..."/></label><label>LOGO / PROFILE IMAGE<input type="file" accept="image/*" onChange={e=>set("logo",e.target.files?.[0]?.name||"")}/></label><button className="primary submit">CONTINUE →</button></form>}
 {step===2&&<form onSubmit={next}><label>COUNTRY<select required value={data.country} onChange={e=>set("country",e.target.value)}><option value="">Select country</option>{countries.map(x=><option key={x}>{x}</option>)}</select></label><label>CATEGORY<select required value={data.category} onChange={e=>set("category",e.target.value)}><option value="">Select category</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><div className="arenaPreview"><span>YOUR LISTING WILL COMPETE IN</span><b>🌍 Global</b><b>📍 {data.country||"Your country"}</b><b>⚡ {data.category||"Your category"}</b></div><div className="formActions"><button type="button" className="secondary" onClick={()=>setStep(1)}>← BACK</button><button className="primary">CONTINUE →</button></div></form>}
 {step===3&&<form onSubmit={e=>{e.preventDefault();setStep(4)}}><label>DEMO BID (USD)<div className="money"><span>$</span><input required type="number" min="10" value={data.bid} onChange={e=>set("bid",e.target.value)}/></div></label><div className="bidPreview"><span>ESTIMATED DEMO POSITION</span><strong>#{Math.max(1,Math.ceil(250-(Number(data.bid)||0)/50))}</strong><small>Global leaderboard · illustrative only</small></div><div className="notice"><b>DEMO MODE</b>No money will be charged. Production ranking will use settled eligible payments only.</div><div className="formActions"><button type="button" className="secondary" onClick={()=>setStep(2)}>← BACK</button><button className="primary">ENTER THE BATTLE →</button></div></form>}</div></main>
}