const leaders=[
{rank:1,name:"NOVA LABS",tag:"AI · USA",bid:"$12,480",move:"+2",icon:"N"},
{rank:2,name:"KICKS PK",tag:"Fashion · Pakistan",bid:"$9,250",move:"+1",icon:"K"},
{rank:3,name:"DUNE EATS",tag:"Food · UAE",bid:"$7,900",move:"NEW",icon:"D"},
{rank:4,name:"PIXELHAUS",tag:"Agency · UK",bid:"$6,440",move:"+3",icon:"P"},
{rank:5,name:"SHOPORA",tag:"Ecommerce · India",bid:"$5,820",move:"-1",icon:"S"}];
const markets=[["🇵🇰","Pakistan","Rs 3.4M"],["🇦🇪","UAE","AED 81K"],["🇺🇸","USA","$48K"],["🇬🇧","UK","£29K"],["🇮🇳","India","₹2.1M"],["🇸🇦","Saudi Arabia","SAR 64K"]];
const cats=["Food & Restaurants","Fashion & Beauty","Technology & Startups","Ecommerce","Creators & Influencers","Agencies & Services","Entertainment","Other"];
export default function Home(){return <main>
<nav><a className="logo" href="#">UP<span>BIDO</span><i>↗</i></a><div className="navlinks"><a href="#battle">Leaderboard</a><a href="#countries">Countries</a><a href="#categories">Categories</a><a href="#hall">Hall of Fame</a></div><a className="ghost btnlink" href="/signin">Sign in</a><a className="primary btnlink" href="/join">JOIN THE BATTLE ↗</a></nav>
<section className="hero"><div className="eyebrow"><b>● DEMO PREVIEW</b> THE INTERNET'S COMPETITIVE BILLBOARD</div><h1>PAY TO BE SEEN.<br/><em>BID TO BE #1.</em></h1><p>Brands, creators and businesses compete in real time for the most visible spots on the internet. The higher the eligible bid, the higher the position.</p><div className="heroBtns"><a className="primary big btnlink" href="/join">GET ON THE BOARD ↗</a><a className="secondary big btnlink" href="#battle">WATCH THE BATTLE ↓</a></div><div className="stats"><div><b>247</b><span>SAMPLE BIDDERS</span></div><div><b>38</b><span>SAMPLE COUNTRIES</span></div><div><b>$184K</b><span>SAMPLE BATTLE VALUE</span></div><div><b>11d 08h</b><span>DEMO TIMER</span></div></div></section>
<section className="ticker"><span>DEMO ACTIVITY</span><marquee>🔥 SAMPLE: KICKS PK took Pakistan #1 &nbsp;&nbsp; • &nbsp;&nbsp; SAMPLE: NOVA LABS increased their bid by $1,200 &nbsp;&nbsp; • &nbsp;&nbsp; SAMPLE: DUNE EATS entered UAE Top 3 &nbsp;&nbsp; • &nbsp;&nbsp; SAMPLE: New challenger joined from London</marquee></section>
<section id="battle" className="wrap"><div className="sectionHead"><div><small>PRODUCT DEMO · GLOBAL BATTLE</small><h2>The world's most<br/>expensive leaderboard.</h2></div><div className="timer">ENDS IN <b>11 : 08 : 21 : 43</b><span>DAYS&nbsp;&nbsp; HRS&nbsp;&nbsp; MIN&nbsp;&nbsp; SEC</span></div></div>
<div className="champ"><div className="crown">♛</div><div className="avatar">N</div><div className="champInfo"><span>DEMO #1 · SPONSORED POSITION</span><h3>NOVA LABS</h3><p>Building the future, one model at a time.</p><div className="chips"><i>🇺🇸 USA</i><i>Technology</i><i>✓ Verified</i></div></div><div className="bid"><span>DEMO BID</span><strong>$12,480</strong><a className="primary btnlink" href="/join">OUTBID → $12,581</a></div></div>
<div className="board">{leaders.slice(1).map(x=><div className="row" key={x.rank}><strong className="rank">#{x.rank}</strong><div className="smAvatar">{x.icon}</div><div className="who"><b>{x.name}</b><span>{x.tag}</span></div><div className="movement">{x.move}</div><div className="amount"><span>CURRENT BID</span><b>{x.bid}</b></div><a className="take btnlink" href="/join">TAKE #{x.rank} ↗</a></div>)}</div><a className="view btnlink" href="/join">JOIN / VIEW BATTLE →</a></section>
<section id="countries" className="dark"><div className="wrap"><small>BATTLES AROUND THE WORLD</small><h2>Pick your arena.</h2><p className="muted">One listing. Multiple leaderboards. Compete locally and globally at the same time.</p><div className="markets">{markets.map(m=><div className="market" key={m[1]}><b className="flag">{m[0]}</b><h3>{m[1]}</h3><span>Battle value</span><strong>{m[2]}</strong><a href="/join">VIEW BATTLE →</a></div>)}</div></div></section>
<section id="categories" className="wrap categories"><small>OWN YOUR INDUSTRY</small><h2>Category battles.</h2><div className="catgrid">{cats.map((c,i)=><div className="cat" key={c}><span>0{i+1}</span><b>{c}</b><i>↗</i></div>)}</div></section>
<section id="hall" className="hall"><div className="demoBadge">SAMPLE RECORDS</div><div><small>HALL OF FAME</small><h2>Rank fades.<br/>Legacy doesn't.</h2><p>Champions are recorded forever. Win a battle and earn your place in UPBIDO history.</p></div><div className="records"><div><span>BIGGEST BID EVER</span><b>$42,900</b><small>ARC ONE · AUG 2026</small></div><div><span>LONGEST #1 STREAK</span><b>19 DAYS</b><small>NOVA LABS · GLOBAL</small></div><div><span>MOST CHAMPIONSHIPS</span><b>7×</b><small>KICKS PK · PAKISTAN</small></div></div></section>
<section className="cta"><small>YOUR COMPETITION IS ALREADY HERE.</small><h2>How high will<br/>you go?</h2><a className="primary big btnlink" href="/join">JOIN THE BATTLE ↗</a><p>Paid ranking. Real visibility. Transparent competition.</p></section>
<footer><a className="logo">UP<span>BIDO</span><i>↗</i></a><p>© 2026 UPBIDO · Rankings are based on eligible paid bids and do not represent quality or popularity.</p></footer>
</main>}