"use client";
import {useEffect,useState} from "react";
export default function Dashboard(){
 const [d,setD]=useState(null);
 useEffect(()=>{try{const x=localStorage.getItem("upbido_demo_listing");if(x)setD(JSON.parse(x))}catch{}},[]);
 const name=d?.name||"Your listing", country=d?.country||"Pakistan", category=d?.category||"Your category", bid=Number(d?.bid||5);
 return <main className="dash"><nav><a className="logo" href="/">UP<span>BIDO</span><i>↗</i></a><a className="primary btnlink" href="/join">INCREASE BID ↗</a></nav><div className="dashWrap"><div className="dashHead"><div><small>DEMO BIDDER DASHBOARD</small><h1>{name}<br/><em>at a glance.</em></h1></div><a href="/">VIEW PUBLIC BATTLE →</a></div>
 <div className="rankGrid bigRanks"><div><span>GLOBAL RANK</span><b>#248</b><small>Demo illustration</small></div><div><span>COUNTRY RANK</span><b>#19</b><small>{country}</small></div><div><span>CATEGORY RANK</span><b>#7</b><small>{category}</small></div></div>
 <div className="dashGrid"><section><small>CURRENT DEMO BID</small><strong>{"$"}{bid.toLocaleString()}</strong><p>UPBIDO uses USD as the standardized ranking currency. Real bids activate only after eligible settled payment when payments are enabled.</p><a className="primary btnlink" href="/join">INCREASE DEMO BID →</a></section><section><small>PERFORMANCE</small><div className="metrics"><div><b>—</b><span>IMPRESSIONS</span></div><div><b>—</b><span>PROFILE VIEWS</span></div><div><b>—</b><span>WEBSITE CLICKS</span></div><div><b>—</b><span>CTR</span></div></div><p>Real analytics start only when production tracking is connected.</p></section></div>
 <section><small>BATTLE WINDOWS</small><div className="metrics"><div><b>TODAY</b><span>FAST DAILY BATTLE</span></div><div><b>MONTH</b><span>CURRENT MONTH</span></div><div><b>ALL-TIME</b><span>LIFETIME PRESTIGE</span></div><div><b>∞</b><span>UNLIMITED RANKING</span></div></div><p>Every eligible participant can retain exact Global, Country and Category positions beyond the public Top 100.</p></section>
 <section><small>WHAT YOUR BID EARNS</small><div className="metrics"><div><b>↑</b><span>HIGHER VISIBILITY</span></div><div><b>🌍</b><span>GLOBAL + COUNTRY + CATEGORY</span></div><div><b>↗</b><span>DIRECT WEBSITE TRAFFIC</span></div><div><b>♛</b><span>STATUS & ACHIEVEMENTS</span></div></div><p>Paid position is advertising visibility, not a quality or popularity rating.</p></section>
 <div className="dashNotice"><b>BIDDER BENEFITS</b> Unlimited ranking, direct outbound links, analytics, shareable rank cards, achievements and Hall of Fame eligibility are part of the planned production experience.</div><div className="dashNotice"><b>DEMO ENVIRONMENT</b> Rank numbers and metrics shown here are illustrative placeholders, not real market activity.</div></div></main>
}